# Nixpacks config for Railway (repo-root). If service root is backend/, Nixpacks will still find this.

[phases.setup]
nixPkgs = ["gcc", "gnumake", "python3", "pkg-config"]

[phases.install]
cmds = [
  "export npm_config_build_from_source=true && npm ci",
  "npm rebuild sqlite3 --build-from-source"
]

[phases.start]
cmd = "npm run start:prod"
