# Ensure native build tools are available and force sqlite3 to build for the target Linux image

[phases.setup]
# Packages required for node-gyp native builds
nixPkgs = ["gcc", "gnumake", "python3", "pkg-config"]

[phases.install]
# Force source build of sqlite3 to avoid wrong prebuilt binary
cmds = [
  "export npm_config_build_from_source=true && npm ci",
  "npm rebuild sqlite3 --build-from-source"
]

[phases.start]
cmd = "npm run start:prod"
